/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 29 16:00:18 GMT 2019
 */

package fr.unice.gfarce.interGraph;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import fr.unice.gfarce.interGraph.Zmodel;
import javax.swing.JLayeredPane;
import javax.swing.text.StyledEditorKit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Zmodel_ESTest extends Zmodel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object[][] objectArray0 = new Object[12][3];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.removeRow(1205);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 11
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[2];
      Object[][] objectArray0 = new Object[6][6];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.setValueAt("fr.unice.gfarce.interGraph.Zmodel", 0, 34);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 34
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][3];
      Object[] objectArray1 = new Object[1];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.addRow(objectArray1);
      // Undeclared exception!
      try { 
        zmodel0.getValueAt(1, 2847);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2847
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Object[][] objectArray0 = new Object[6][5];
      String[] stringArray0 = new String[11];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.setValueAt((Object) null, 1, 1);
      assertEquals(11, zmodel0.getColumnCount());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      Object[][] objectArray0 = new Object[2][3];
      objectArray0[0] = (Object[]) stringArray0;
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      Object object0 = zmodel0.getValueAt(0, 0);
      assertEquals("", object0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][1];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getRowCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Object[][] objectArray0 = new Object[6][6];
      String[] stringArray0 = new String[8];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getRowCount();
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][1];
      String[] stringArray0 = new String[3];
      stringArray0[0] = "KIS@";
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      String string0 = zmodel0.getColumnName(0);
      assertEquals("KIS@", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[2];
      stringArray0[1] = "";
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      String string0 = zmodel0.getColumnName(1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[0];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getColumnCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][3];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getColumnCount();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      Integer integer0 = JLayeredPane.DRAG_LAYER;
      // Undeclared exception!
      try { 
        zmodel0.setValueAt(integer0, 158, 158);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.addRow(stringArray0);
      StyledEditorKit.UnderlineAction styledEditorKit_UnderlineAction0 = new StyledEditorKit.UnderlineAction();
      // Undeclared exception!
      try { 
        zmodel0.setValueAt(styledEditorKit_UnderlineAction0, 0, 0);
        fail("Expecting exception: ArrayStoreException");
      
      } catch(ArrayStoreException e) {
         //
         // javax.swing.text.StyledEditorKit$UnderlineAction
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][1];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.removeRow((-2118));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][9];
      String[] stringArray0 = new String[0];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.removeRow((-2118));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][3];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.removeRow((-2118));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[6];
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getValueAt((-811), (-1007));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][1];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.getColumnName(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getColumnName(3038);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3038
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Zmodel zmodel0 = new Zmodel((Object[][]) null, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.afficheData((Object[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[11];
      Object[][] objectArray0 = new Object[2][5];
      objectArray0[0] = (Object[]) stringArray0;
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.afficheData(objectArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][3];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.addRow((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getRowCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.getColumnCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][3];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      zmodel0.afficheData(objectArray0);
      assertEquals(1, zmodel0.getRowCount());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.addRow(stringArray0);
      zmodel0.addRow(stringArray0);
      zmodel0.removeRow(0);
      assertEquals(1, zmodel0.getRowCount());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][1];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      boolean boolean0 = zmodel0.isCellEditable((-4064), (-4064));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      String string0 = zmodel0.getColumnName(1);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Object[][] objectArray0 = new Object[6][5];
      String[] stringArray0 = new String[11];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      Object object0 = zmodel0.getValueAt(1, 1);
      assertNull(object0);
  }
}
