/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 25 20:54:16 GMT 2019
 */

package fr.unice.gfarce.interGraph;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import fr.unice.gfarce.interGraph.Zmodel;
import java.awt.MultipleGradientPaint;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.plaf.synth.SynthDesktopPaneUI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Zmodel_ESTest extends Zmodel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object[][] objectArray0 = new Object[2][7];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.removeRow(1);
      assertEquals(1, zmodel0.getRowCount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      String[] stringArray0 = new String[8];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      MultipleGradientPaint.CycleMethod multipleGradientPaint_CycleMethod0 = MultipleGradientPaint.CycleMethod.REPEAT;
      zmodel0.setValueAt(multipleGradientPaint_CycleMethod0, 0, 4);
      assertEquals(8, zmodel0.getColumnCount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      Object object0 = zmodel0.getValueAt(0, 2);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][5];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.removeRow(0);
      int int0 = zmodel0.getRowCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][5];
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getRowCount();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      String[] stringArray0 = new String[2];
      stringArray0[0] = "Ky2@{ `p1}6PGizP";
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      String string0 = zmodel0.getColumnName(0);
      assertEquals("Ky2@{ `p1}6PGizP", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][6];
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      String string0 = zmodel0.getColumnName(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Object[][] objectArray0 = new Object[6][8];
      String[] stringArray0 = new String[0];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getColumnCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      int int0 = zmodel0.getColumnCount();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Zmodel zmodel0 = new Zmodel((Object[][]) null, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.setValueAt(zmodel0, 3797, 3797);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[8];
      Object[][] objectArray0 = new Object[1][8];
      objectArray0[0] = (Object[]) stringArray0;
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      JCheckBoxMenuItem jCheckBoxMenuItem0 = new JCheckBoxMenuItem("Indice = ");
      // Undeclared exception!
      try { 
        zmodel0.setValueAt(jCheckBoxMenuItem0, 0, 0);
        fail("Expecting exception: ArrayStoreException");
      
      } catch(ArrayStoreException e) {
         //
         // javax.swing.JCheckBoxMenuItem
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Object[][] objectArray0 = new Object[13][8];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        zmodel0.setValueAt(object0, (-957), (-957));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -957
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Object[][] objectArray0 = new Object[17][8];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.removeRow((-263));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object[][] objectArray0 = new Object[0][5];
      String[] stringArray0 = new String[0];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.removeRow(18);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.removeRow((-2053));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getValueAt(1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Object[][] objectArray0 = new Object[30][8];
      String[] stringArray0 = new String[20];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getValueAt(2703, 2703);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2703
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Object[][] objectArray0 = new Object[14][8];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.getColumnName(192);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      String[] stringArray0 = new String[2];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getColumnName((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.afficheData((Object[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[16];
      Object[][] objectArray0 = new Object[4][8];
      objectArray0[0] = (Object[]) stringArray0;
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.afficheData(objectArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][8];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.addRow((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      // Undeclared exception!
      try { 
        zmodel0.getRowCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Object[][] objectArray0 = new Object[11][8];
      Zmodel zmodel0 = new Zmodel(objectArray0, (String[]) null);
      // Undeclared exception!
      try { 
        zmodel0.getColumnCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.Zmodel", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Object[][] objectArray0 = new Object[3][8];
      String[] stringArray0 = new String[10];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.afficheData(objectArray0);
      assertEquals(3, zmodel0.getRowCount());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Object[][] objectArray0 = new Object[17][8];
      String[] stringArray0 = new String[4];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.removeRow(0);
      assertEquals(16, zmodel0.getRowCount());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][1];
      String[] stringArray0 = new String[6];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      boolean boolean0 = zmodel0.isCellEditable((-303), (-303));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Object[][] objectArray0 = new Object[3][8];
      String[] stringArray0 = new String[10];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      SynthDesktopPaneUI synthDesktopPaneUI0 = new SynthDesktopPaneUI();
      zmodel0.setValueAt(synthDesktopPaneUI0, 1, 1);
      Object object0 = zmodel0.getValueAt(1, 1);
      assertSame(object0, synthDesktopPaneUI0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Object[][] objectArray0 = new Object[1][1];
      String[] stringArray0 = new String[6];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      String string0 = zmodel0.getColumnName(1);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Object[][] objectArray0 = new Object[17][8];
      String[] stringArray0 = new String[4];
      Zmodel zmodel0 = new Zmodel(objectArray0, stringArray0);
      zmodel0.addRow(stringArray0);
      assertEquals(18, zmodel0.getRowCount());
  }
}
