/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 06 17:05:52 GMT 2019
 */

package net.sourceforge.squirrel_sql.fw.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.FileFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FilenameFilter;
import java.net.URI;
import net.sourceforge.squirrel_sql.fw.util.FileExtensionFilter;
import net.sourceforge.squirrel_sql.fw.util.FileWrapper;
import net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileWrapperImpl_ESTest extends FileWrapperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      FileWrapperImpl fileWrapperImpl1 = new FileWrapperImpl(fileWrapperImpl0);
      int int0 = fileWrapperImpl0.compareTo(fileWrapperImpl1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FileWrapper fileWrapper0 = FileWrapperImpl.createTempFile("v7T", "", (FileWrapper) null);
      assertEquals("v7T0", fileWrapper0.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      URI uRI0 = MockURI.aFileURI;
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(uRI0);
      assertEquals("foo.bar", fileWrapperImpl0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn((URI) null).when(file0).toURI();
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(file0);
      URI uRI0 = fileWrapperImpl0.toURI();
      assertNull(uRI0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("FcQs");
      String string0 = fileWrapperImpl0.toString();
      assertEquals("FcQs", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      String string0 = fileWrapperImpl0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("-jBRYBF>%,$ph?|", "-jBRYBF>%,$ph?|");
      fileWrapperImpl0.getFileOutputStream();
      boolean boolean0 = fileWrapperImpl0.setReadOnly();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("0_Z[tOiiK3#X", "0_Z[tOiiK3#X");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("0_Z[tOiiK3#X", ", ", fileWrapperImpl0);
      fileWrapperImpl1.setLastModified(1L);
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/0_Z[tOiiK3#X/0_Z[tOiiK3#X/0_Z[tOiiK3#X0, ", fileWrapperImpl1.getPath());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("1>]W+Y{}_nU'ew+'");
      boolean boolean0 = fileWrapperImpl0.renameTo(fileWrapperImpl0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(", ", "");
      boolean boolean0 = fileWrapperImpl0.mkdirs();
      assertTrue(boolean0);
      
      boolean boolean1 = fileWrapperImpl0.mkdirs();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "A]w%");
      boolean boolean0 = fileWrapperImpl0.mkdir();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("{h\u0004)5WM");
      String[] stringArray0 = new String[5];
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter(" (", stringArray0);
      FileWrapper[] fileWrapperArray0 = fileWrapperImpl0.listFiles((FilenameFilter) fileExtensionFilter0);
      assertNull(fileWrapperArray0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter("/", stringArray0);
      FileWrapper[] fileWrapperArray0 = fileWrapperImpl0.listFiles((FilenameFilter) fileExtensionFilter0);
      assertEquals(2, fileWrapperArray0.length);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      String[] stringArray0 = new String[4];
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter("", stringArray0);
      FileWrapper[] fileWrapperArray0 = fileWrapperImpl0.listFiles((FileFilter) fileExtensionFilter0);
      assertEquals(2, fileWrapperArray0.length);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      String[] stringArray0 = new String[9];
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter("", stringArray0);
      FileWrapper[] fileWrapperArray0 = fileWrapperImpl0.listFiles((FileFilter) fileExtensionFilter0);
      assertEquals(0, fileWrapperArray0.length);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("@", "@");
      FileWrapperImpl fileWrapperImpl1 = new FileWrapperImpl(fileWrapperImpl0, "@");
      fileWrapperImpl1.getFileWriter();
      fileWrapperImpl0.listFiles();
      assertTrue(fileWrapperImpl0.canRead());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      FileWrapper[] fileWrapperArray0 = fileWrapperImpl0.listFiles();
      assertEquals(0, fileWrapperArray0.length);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl.createTempFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "", fileWrapperImpl0);
      String[] stringArray0 = new String[7];
      stringArray0[0] = "o6,9>Sjvkd";
      stringArray0[1] = "";
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter("", stringArray0);
      String[] stringArray1 = fileWrapperImpl0.list((FilenameFilter) fileExtensionFilter0);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      String[] stringArray0 = new String[1];
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter("", stringArray0);
      String[] stringArray1 = fileWrapperImpl0.list((FilenameFilter) fileExtensionFilter0);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      String[] stringArray0 = fileWrapperImpl0.list();
      assertEquals(2, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("T[0M?7bL");
      fileWrapperImpl0.mkdirs();
      String[] stringArray0 = fileWrapperImpl0.list();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("5]59t])");
      long long0 = fileWrapperImpl0.lastModified();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("T[0M?7bL");
      fileWrapperImpl0.mkdirs();
      long long0 = fileWrapperImpl0.lastModified();
      assertEquals(1392409281320L, long0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileExtensionFilter", "net.sourceforge.squirrel_sql.fw.util.FileExtensionFilter");
      boolean boolean0 = fileWrapperImpl0.isHidden();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("T[0M?7bL");
      boolean boolean0 = fileWrapperImpl0.mkdirs();
      boolean boolean1 = fileWrapperImpl0.isFile();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("hOO", "net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      fileWrapperImpl0.isDirectory();
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/hOO/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", fileWrapperImpl0.getPath());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("1>]W+H^}_nU'e!+'", "1>]W+H^}_nU'e!+'");
      boolean boolean0 = fileWrapperImpl0.isAbsolute();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(file0).getPath();
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(file0);
      String string0 = fileWrapperImpl0.getPath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      String string0 = fileWrapperImpl0.getPath();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("/^ezw9?e-H@D``;1~?");
      FileWrapper fileWrapper0 = fileWrapperImpl0.getParentFile();
      assertEquals("", fileWrapper0.getName());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("'", "'");
      String string0 = fileWrapperImpl0.getParent();
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/'", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn("").when(file0).getParent();
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(file0);
      String string0 = fileWrapperImpl0.getParent();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      String string0 = fileWrapperImpl0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("0_Z[tiK3#", "0_Z[tiK3#");
      fileWrapperImpl0.getPrintWriter();
      FileReader fileReader0 = fileWrapperImpl0.getFileReader();
      assertNotNull(fileReader0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "", fileWrapperImpl0);
      fileWrapperImpl1.getFileInputStream();
      assertEquals("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl0", fileWrapperImpl1.getName());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      byte[] byteArray0 = new byte[9];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      FileInputStream fileInputStream0 = fileWrapperImpl0.getFileInputStream();
      assertEquals(9, fileInputStream0.available());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(file0).getCanonicalPath();
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(file0);
      String string0 = fileWrapperImpl0.getCanonicalPath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn("").when(file0).getCanonicalPath();
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(file0);
      String string0 = fileWrapperImpl0.getCanonicalPath();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MockFile mockFile0 = new MockFile(" ");
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(mockFile0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(" ");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, " ");
      FileWrapper fileWrapper0 = fileWrapperImpl0.getCanonicalFile();
      assertTrue(fileWrapper0.exists());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      FileWrapper fileWrapper0 = fileWrapperImpl0.getCanonicalFile();
      assertFalse(fileWrapper0.isHidden());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("0_Z[tOiiK3#X", "0_Z[tOiiK3#X");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("0_Z[tOiiK3#X", ", ", fileWrapperImpl0);
      fileWrapperImpl1.getBufferedReader();
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/0_Z[tOiiK3#X/0_Z[tOiiK3#X/0_Z[tOiiK3#X0, ", fileWrapperImpl1.toString());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(file0).getAbsolutePath();
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(file0);
      String string0 = fileWrapperImpl0.getAbsolutePath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MockFile mockFile0 = new MockFile(" ");
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(mockFile0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(" ");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, " ");
      FileWrapper fileWrapper0 = fileWrapperImpl0.getAbsoluteFile();
      assertTrue(fileWrapper0.isAbsolute());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(".#buy#Ab7QYa8");
      FileWrapper fileWrapper0 = fileWrapperImpl0.getAbsoluteFile();
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/.#buy#Ab7QYa8", fileWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "", fileWrapperImpl0);
      fileWrapperImpl1.exists();
      assertEquals("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl0", fileWrapperImpl1.getName());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("");
      boolean boolean0 = fileWrapperImpl0.delete();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("0_Z[tOiiK3#X/0_Z[tOiiK3#X/0_Z[tOiiK3#X0, ");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "0_Z[tOiiK3#X");
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("0_Z[tOiiK3#X", "0_Z[tOiiK3#X");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("0_Z[tOiiK3#X", ", ", fileWrapperImpl0);
      assertEquals(13L, fileWrapperImpl1.length());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("-h/.Ai", (String) null, fileWrapperImpl0);
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl/-h", fileWrapperImpl1.getParent());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl0");
      FileSystemHandling.createFolder(evoSuiteFile0);
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "", fileWrapperImpl0);
      assertFalse(fileWrapperImpl1.isFile());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      FileWrapper fileWrapper0 = FileWrapperImpl.createTempFile(".-|D[:i^ClmG", ".-|D[:i^ClmG", (FileWrapper) null);
      assertEquals("/tmp/.-|D[:i^ClmG0.-|D[:i^ClmG", fileWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl01O%4L}U(bMWHBW(V~");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "x-rl^zQWDZy>]7%|x");
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "", fileWrapperImpl0);
      assertEquals("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl0", fileWrapperImpl1.toString());
      
      FileWrapper fileWrapper0 = FileWrapperImpl.createTempFile("/home/pderakhshanfar/evosuite-model-seeding-ee/evosuite-model-seeding-empirical-evaluation/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl/net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl0", "O%4L}U(bMWHBW(V~");
      assertEquals("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl01O%4L}U(bMWHBW(V~", fileWrapper0.getName());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      FileWrapper fileWrapper0 = FileWrapperImpl.createTempFile(".D=_Lcz5i", "p.|o&I");
      assertEquals("/tmp/.D=_Lcz5i0p.|o&I", fileWrapper0.getPath());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/1>]W+Y{}_nU'ew+'01>]W+Y{}_nU'ew+'");
      FileSystemHandling.createFolder(evoSuiteFile0);
      FileWrapper fileWrapper0 = FileWrapperImpl.createTempFile("1>]W+Y{}_nU'ew+'", "1>]W+Y{}_nU'ew+'");
      assertEquals("/tmp/1>]W+Y{}_nU'ew+'01>]W+Y{}_nU'ew+'", fileWrapper0.getPath());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl");
      FileWrapperImpl fileWrapperImpl1 = FileWrapperImpl.createTempFile("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", "", fileWrapperImpl0);
      FileWrapperImpl fileWrapperImpl2 = new FileWrapperImpl(fileWrapperImpl1, "O%4L}U(bMWHBW(V~");
      boolean boolean0 = fileWrapperImpl2.createNewFile();
      assertFalse(fileWrapperImpl0.isFile());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("0_Z[tOiiK3#X");
      int int0 = fileWrapperImpl0.compareTo(fileWrapperImpl0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      MockFile mockFile0 = new MockFile(" ");
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl(mockFile0);
      fileWrapperImpl0.getFileWriter();
      boolean boolean0 = fileWrapperImpl0.canWrite();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("@", "@");
      fileWrapperImpl0.mkdirs();
      boolean boolean0 = fileWrapperImpl0.canRead();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.toURL();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.toURI();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.setReadOnly();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.setLastModified(1012L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("1>]W+H^}_nU'e!+'", "1>]W+H^}_nU'e!+'");
      // Undeclared exception!
      try { 
        fileWrapperImpl0.setLastModified((-1L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Negative time
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      FileWrapper fileWrapper0 = mock(FileWrapper.class, new ViolatedAssumptionAnswer());
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "A]w%");
      // Undeclared exception!
      try { 
        fileWrapperImpl0.renameTo(fileWrapper0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // net.sourceforge.squirrel_sql.fw.util.FileWrapper$MockitoMock$1766605434 cannot be cast to net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.mkdirs();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.mkdir();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.listFiles((FilenameFilter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      String[] stringArray0 = new String[2];
      FileExtensionFilter fileExtensionFilter0 = new FileExtensionFilter(", ", stringArray0);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.listFiles((FileFilter) fileExtensionFilter0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.listFiles();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.length();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.isFile();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.isAbsolute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      try { 
        fileWrapperImpl0.getPrintWriter();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getPath();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getParentFile();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getParent();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getFileWriter();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      try { 
        fileWrapperImpl0.getFileWriter();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getFileReader();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl("", "");
      try { 
        fileWrapperImpl0.getFileOutputStream();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getFileInputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      FileWrapperImpl fileWrapperImpl0 = new FileWrapperImpl((File) null);
      // Undeclared exception!
      try { 
        fileWrapperImpl0.getCanonicalPath();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.FileWrapperImpl", e);
      }
  }
}
