/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 29 08:12:07 GMT 2019
 */

package fr.unice.gfarce.interGraph;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import fr.unice.gfarce.interGraph.CreerUnEtudiantAction;
import fr.unice.gfarce.interGraph.FenetrePrincipale;
import fr.unice.gfarce.interGraph.Zmodel;
import fr.unice.gfarce.main.Controler;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreerUnEtudiantAction_ESTest extends CreerUnEtudiantAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CreerUnEtudiantAction creerUnEtudiantAction0 = new CreerUnEtudiantAction((FenetrePrincipale) null, "JY)FX6G1^e\"cjl=_", (Controler) null);
      String[] stringArray0 = new String[7];
      JTextField jTextField0 = new JTextField("fr.unice.gfarce.identity.Identite");
      FenetrePrincipale.textFieldNomEtudiant = jTextField0;
      Zmodel zmodel0 = new Zmodel((Object[][]) null, stringArray0);
      ActionEvent actionEvent0 = new ActionEvent(zmodel0, (-95), "r2)DYVIvex");
      // Undeclared exception!
      try { 
        creerUnEtudiantAction0.actionPerformed(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fr.unice.gfarce.interGraph.CreerUnEtudiantAction", e);
      }
  }
}
