/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 23 13:07:20 GMT 2019
 */

package module;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.Stack;
import module.Kernel;
import module.Message;
import module.MessageFactory;
import module.Module;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Kernel_ESTest extends Kernel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      kernel0.loadModule("module.Kernel");
      try { 
        kernel0.unloadModule("module.Kernel");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // mod=module.Kernel
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      try { 
        kernel0.unloadModule(".j,gx(=,pgZ>T}@PI");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // mod=.j,gx(=,pgZ>T}@PI
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      kernel0.unsubscribe((Module) null, "");
      kernel0.getThread();
      kernel0.getThread();
      Message message0 = MessageFactory.createUnloadMessage((String) null);
      message0.ref();
      message0.unref();
      message0.unref();
      message0.unref();
      message0.unref();
      message0.unref();
      message0.unref();
      // Undeclared exception!
      try { 
        kernel0.sendMessageNotify((Collection<Module>) null, message0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      Message message0 = new Message();
      Message message1 = new Message();
      message1.messageID = (-342L);
      try { 
        kernel0.processMessage(message1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      Message message0 = new Message();
      message0.setSender("Player.unpack(): *** WARNING *** [IO] failed to unpack data: ");
      message0.setHeader("Player.unpack(): *** WARNING *** [IO] failed to unpack data: ");
      message0.setBody(kernel0);
      kernel0.receiveMessage(message0);
      try { 
        kernel0.loadModule("ju");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassNotFoundException: Class 'ju.class' should be in target project, but could not be found!
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      kernel0.getKernel();
      Stack<Module> stack0 = new Stack<Module>();
      String string0 = "XJTl/^eP|_(";
      Message message0 = MessageFactory.createConnectionDroppedMessage((-2877), "XJTl/^eP|_(");
      message0.getHeader();
      message0.getBody();
      Message message1 = new Message();
      try { 
        kernel0.sendMessage(message1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.NullPointerException
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      try { 
        kernel0.loadModule((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.NullPointerException
         //
         verifyException("module.Kernel", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Kernel kernel0 = new Kernel();
      String string0 = "";
      try { 
        kernel0.loadModule("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassNotFoundException: 
         //
         verifyException("module.Kernel", e);
      }
  }
}
